### ISSUE TITLE
The plugin does not work in IntelliJ IDEA 2025.3.1.1

### ISSUE THREAD

**Issue by giovannivelludo** [jbangdev/jbang-idea#142]
**Describe the bug**
I opened a simple project containing a single Java file, and the plugin crashed. Dependencies were therefore not resolved.

**To Reproduce**
In an empty folder, run `jbang init -t cli hellocli.java`
Then check that the program runs with `jbang hellocli.java Test`
Open the folder in IntelliJ, and open hellocli.java.

**Expected behavior**
The plugin should not crash and dependencies should be resolved.

**JBang version**
```
[jbang] [0:135] jbang version 0.135.1
Cache: /Users/velludo.giovanni/.jbang/cache
Config: /Users/velludo.giovanni/.jbang
Repository: /Users/velludo.giovanni/.m2/repository
Java: /opt/homebrew/Cellar/openjdk@17/17.0.17/libexec/openjdk.jdk/Contents/Home [17.0.17]
OS: mac
Arch: aarch64
Shell: bash
Native Image: false
0.135.1
```

**Additional context**
Stacktrace:
```stacktrace
java.lang.NoClassDefFoundError: org/jetbrains/kotlin/psi/psiUtil/PsiUtilsKt
	at dev.jbang.idea.run.JBangRunConfigurationProducer.setupConfigurationFromContext(JBangRunConfigurationProducer.kt:36)
	at dev.jbang.idea.run.JBangRunConfigurationProducer.setupConfigurationFromContext(JBangRunConfigurationProducer.kt:15)
	at com.intellij.execution.actions.RunConfigurationProducer.createConfigurationFromContext(RunConfigurationProducer.java:99)
	at com.intellij.execution.actions.PreferredProducerFind.doGetConfigurationsFromContext(PreferredProducerFind.java:122)
	at com.intellij.execution.actions.PreferredProducerFind.getConfigurationsFromContext(PreferredProducerFind.java:103)
	at com.intellij.execution.actions.ConfigurationContext.createConfigurationsFromContext(ConfigurationContext.java:428)
	at com.intellij.execution.actions.ExecutorAction.getRunConfigsForCurrentFile(ExecutorAction.java:312)
	at com.intellij.execution.actions.ExecutorAction.getRunCurrentFileActionStatus(ExecutorAction.java:250)
	at com.intellij.execution.actions.ExecutorAction.getRunCurrentFileActionStatus(ExecutorAction.java:227)
	at com.intellij.execution.actions.ExecutorAction.update(ExecutorAction.java:152)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.updateAction$lambda$0(ActionUtil.kt:263)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.updateAction(ActionUtil.kt:271)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$result$1$1$1.invoke(ActionUpdater.kt:528)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$result$1$1$1.invoke(ActionUpdater.kt:527)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$callAction$2$1.invoke(ActionUpdater.kt:147)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:111)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable$lambda$0(InternalReadAction.kt:101)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$0$0$0(cancellableReadAction.kt:32)
	at com.intellij.platform.locking.impl.NestedLocksThreadingSupport.tryRunReadAction(NestedLocksThreadingSupport.kt:902)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1237)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$0$0(cancellableReadAction.kt:30)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:152)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$0(cancellableReadAction.kt:28)
	at com.intellij.concurrency.ThreadContext.installThreadContext(threadContext.kt:305)
	at com.intellij.concurrency.ThreadContext.installThreadContext$default(threadContext.kt:303)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:24)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:100)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:86)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:73)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:15)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$3.invokeSuspend(InternalReadAction.kt:35)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$3.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$3.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:44)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:285)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:34)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:66)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadActionUndispatched(coroutines.kt:84)
	at com.intellij.openapi.application.CoroutinesKt.readActionUndispatched(coroutines.kt:71)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$callAction$$inlined$useWithScope$1.invokeSuspend(trace.kt:114)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$callAction$$inlined$useWithScope$1.invoke(trace.kt)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$callAction$$inlined$useWithScope$1.invoke(trace.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:44)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.kt:925)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.access$callAction(ActionUpdater.kt:77)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$result$1$1.invokeSuspend(ActionUpdater.kt:527)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$result$1$1.invoke(ActionUpdater.kt)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$result$1$1.invoke(ActionUpdater.kt)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$$inlined$retryOnAwaitSharedData$1.invokeSuspend(ActionUpdater.kt:924)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$$inlined$retryOnAwaitSharedData$1.invoke(ActionUpdater.kt)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$$inlined$retryOnAwaitSharedData$1.invoke(ActionUpdater.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:44)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.updateAction(ActionUpdater.kt:978)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.kt:369)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.access$expandGroupChild(ActionUpdater.kt:77)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$doExpandActionGroup$2$expandResult$1$1.invokeSuspend(ActionUpdater.kt:288)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:610)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runDefaultDispatcherTask(CoroutineScheduler.kt:1194)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:906)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:775)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:762)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.kotlin.psi.psiUtil.PsiUtilsKt PluginClassLoader(plugin=PluginMainDescriptor(name=JBang, id=dev.jbang.intellij.JBangPlugin, version=0.25.1, isBundled=false, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.3/plugins/jbang-idea-plugin), packagePrefix=null, state=active, parents=ContentModuleDescriptor(id=intellij.profiler.ultimate, package=com.intellij.profiler.ultimate) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.jvm.dfa.analysis.ui, package=com.intellij.jvm.dfa.analysis.ui) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.java.terminal, package=com.intellij.java.terminal) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.java.performancePlugin, package=com.intellij.java.performancePlugin) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.java.debugger.impl.frontend, package=com.intellij.java.debugger.impl.frontend) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.java.debugger.impl.backend, package=com.intellij.java.debugger.impl.backend) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.java.psi, loadingRule=EMBEDDED) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.java.psi.impl, loadingRule=EMBEDDED) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.java.syntax, loadingRule=EMBEDDED) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.java.execution.impl.shared, loadingRule=EMBEDDED) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.java.debugger.impl.shared, loadingRule=EMBEDDED) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.java.frontback.impl, loadingRule=EMBEDDED) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.java.frontback.psi.impl, loadingRule=EMBEDDED) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.java.frontback.psi, loadingRule=EMBEDDED) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.platform.vcs.log.graph) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/lib), ContentModuleDescriptor(id=intellij.platform.vcs.log) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/lib), ContentModuleDescriptor(id=intellij.platform.vcs.dvcs) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/lib), ContentModuleDescriptor(id=intellij.platform.vcs.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/lib), ContentModuleDescriptor(id=intellij.platform.vcs.log.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/lib), ContentModuleDescriptor(id=intellij.platform.vcs.dvcs.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/lib), ContentModuleDescriptor(id=intellij.platform.collaborationTools) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/lib), ContentModuleDescriptor(id=intellij.java.jam.impl) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.java.langInjection.jps) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.java.langInjection) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.java.execution.impl.backend) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.java.execution.impl.frontend) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.jvm.analysis.impl) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.java.vcs) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.java.unscramble) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.java.featuresTrainer) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.java.structuralSearch) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.java.duplicatesDetection) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), ContentModuleDescriptor(id=intellij.java.duplicates.analysis) <- PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), PluginMainDescriptor(name=Artifacts Repository Search, id=org.jetbrains.idea.reposearch, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/repository-search), PluginMainDescriptor(name=Java, id=com.intellij.java, version=253.29346.240, isBundled=true, path=~/Applications/IntelliJ IDEA.app/Contents/plugins/java), )
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:149)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 71 more
```

**Comment by wfouche** [comment]
Version 0.25.2 of the plugin is now available:

- https://github.com/jbangdev/jbang-idea/releases/tag/v0.25.2

Please test with the updated plugin, and let us know if the issue is resolved or not.

**Comment by giovannivelludo** [comment]
@wfouche I did so and the issue persists

**Comment by wfouche** [comment]
I'm also unable to resolve //DEPS with the JBang plugin in IntelliJ.

```java
///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS info.picocli:picocli:4.6.3


import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Parameters;

import java.util.concurrent.Callable;

@Command(name = "hello", mixinStandardHelpOptions = true, version = "hello 0.1",
        description = "hello made with jbang")
class hello implements Callable<Integer> {

    @Parameters(index = "0", description = "The greeting to print", defaultValue = "World!")
    private String greeting;

    public static void main(String... args) {
        int exitCode = new CommandLine(new hello()).execute(args);
        System.exit(exitCode);
    }

    @Override
    public Integer call() throws Exception { // your business logic goes here...
        System.out.println("Hello " + greeting);
        return 0;
    }
}
```

<img width="416" height="147" alt="Image" src="https://github.com/user-attachments/assets/5a77b9c7-baae-47e1-99aa-bfde7fcca1bf" />

**Comment by wfouche** [comment]
@linux-china , is the plugin working in your environment at the moment?  

Not having any luck using 0.25.2 (or 0.25.1) with IntelliJ 2025.3.4  

- In //DEPS sections, GAVs are not resolved.
- Classes imported from JARs in //DEPS are not resolved by  IntelliJ IDEA.

<img width="629" height="417" alt="Image" src="https://github.com/user-attachments/assets/cc964b28-f674-4774-8766-575e7e798ba7" />

```java
///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS io.leego:banana:2.1.0

import java.lang.System;

import io.leego.banana.BananaUtils;
import io.leego.banana.Font;

public class hello {

    public static void main(String... args) {
        String text0 = "Hello World!";
        String text1 = BananaUtils.bananaify(text0, Font.STANDARD);
        System.out.println(text1);
    }
}
```

**Comment by linux-china** [comment]
@wfouche  theme problem? 

<img width="1768" height="1494" alt="Image" src="https://github.com/user-attachments/assets/2bc8a00a-bbd2-43fb-8859-5fb4f869403c" />

**Comment by wfouche** [comment]
> @wfouche theme problem?

No, definitely not.

Also in your example screenshot, the BananaUtils and Font classes are not recognized by IntelliJ.

Try typing Font.   and you'll see that it does not give you any class member options.

**Comment by linux-china** [comment]
@wfouche  got.  You should click `Sync JBang DEPS to module` from popup menu, and sync dependencies first. 

<img width="842" height="492" alt="Image" src="https://github.com/user-attachments/assets/0432d5d4-37f1-49ca-a5aa-066455b46149" />

After sync, and it will work well.

<img width="842" height="492" alt="Image" src="https://github.com/user-attachments/assets/acc45509-5521-419e-bbcc-12794de940cc" />

**Comment by wfouche** [comment]
@linux-china , thank you!

So one should right-click in the source file for the pop-up menu to be displayed and then select "Sync JBang DEPS to Module".

I did not know that.

But now it works fine.
